### API TEST ###
GET http://localhost:8080/api/test 
Content-Type: application/application/json

### Create Testimonial ###
POST http://localhost:8080/api/testimonial/create/testimonial 
Content-Type: application/json

{
      "name":"John Smith",
      "post":"CEO, BlackArrow",
      "description":"Stop wasting time and money designing and managing a website that doesn’t get results. Happiness guaranteed! Stop wasting time and money designing and managing a website that doesn’t get results. Happiness guaranteed!"
}

### get all testimonials ###
GET http://localhost:8080/api/testimonial/view-all/testimonials/1
Content-Type: application/json


### update testimonials ###
PATCH http://localhost:8080/api/testimonial/update/testimonial/61042685918775521cb5e4dc
Content-Type: application/json

{
      "post":"CMO, RStechnologies"
}

### delete testimonials ###
DELETE http://localhost:8080/api/testimonial/delete/testimonial/6103765ddbf61c0d10878e5a
Content-Type: application/json

{
      "status": 0
}
